# Generated by Django 4.2.10 on 2024-03-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_rename_price_menu_pricetotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='priceTotal',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp1.menucategory'),
        ),
    ]
